# Título, descripción y detalles del autor
title: La sala del lado
email: cecastillo@uchile.cl
description: >- # esta es la descripción que se mostrará en los buscadores
  Un blog de escritura cinéfila.
baseurl: "/la-sala-del-lado/" # si tu sitio está en un subdirectorio, p. ej. /blog
url: "https://cecastillo-1987.github.io" # la URL base de tu sitio
github_username: cecastillo-1987

# Nueva configuración de idioma
locale: "es-es"

# Configuración de construcción
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Opcional: Personalizar el autor para el tema "So Simple"
# Detalles del autor
authors:
  cesar:
    name: "César Castillo"
    bio: "Una biografía corta del autor."
    # avatar: "/assets/images/avatar.jpg"

 
# Opcional: Logo para la cabecera (masthead)
logo: "/assets/images/corisco.jpeg"


# Opcional: Otras configuraciones del tema
# Puedes encontrar más opciones en la documentación oficial del tema

# Site skin
skin: "/assets/css/skins/light.css"


# Configuración de Google Fonts
google_fonts:
google_fonts:
  - name: "PLayfair Display"
    weights: "400,400i,700,700i"
  - name: "Lato"
    weights: "400,400i,700,700i"